version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
  api:
    image: "figarrido/custom-node"
    working_dir: /home/node/app
    depends_on:
      - nsqlookupd
      - manager
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:8080
    command: "yarn api"
  manager:
    image: "figarrido/custom-node"
    working_dir: /home/node/app
    depends_on:
      - nsqlookupd
    volumes:
      - ./:/home/node/app
    command: "yarn manager"
